dbinfo:
   dbip: "203.3.230.50"
   dbname: "allinone"
   dbuser: "allinone"
   dbpasswd: "Kydl@2020"
   dbport: "3306"
   charset: "utf8"
   showsql: true
   #showsql: false
appinfo:
   app_name: "allinone"
   app_mode: "debug"
   app_host: "localhost"
   app_port: "5757"